### ISSUE TITLE
Bower resolver not found: bower-art-resolver in Windows CMD

### ISSUE THREAD

**Issue by marslo** [jfrog/bower-art-resolver#27]
### My environment
- System: Windows 10
- NodeJS: Downloaded at [here](https://nodejs.org/en/download/). 
- System Environment Variables:
```bat
C:\> set | grep node
Path=...;C:\Program Files\Java\jdk1.8.0_101\bin;C:\Marslo\MyProgramFiles\nodejs\;C:\Users\mycomputer\AppData\Roaming\npm;c:\Users\mycomputer\node_modules\.bin\;c:\Users\mycomputer\node_modules\node_modules\bower-art-resolver\
```
### Error:
```bat

C:\>bower install bootstrap --verbose
bower                      ENORESOLVER Bower resolver not found: bower-art-resolver

Stack trace:
Error: Bower resolver not found: bower-art-resolver
    at createError (c:\Users\mycomputer\node_modules\bower\lib\util\createError.js:4:15)
    at c:\Users\mycomputer\node_modules\bower\lib\core\resolverFactory.js:67:27
    at Array.map (native)
    at c:\Users\mycomputer\node_modules\bower\lib\core\resolverFactory.js:58:46
    at c:\Users\mycomputer\node_modules\bower\lib\core\resolverFactory.js:35:24
From previous event:
    at PackageRepository.fetch (c:\Users\mycomputer\node_modules\bower\lib\core\PackageRepository.js:46:6)
    at Manager._fetch (c:\Users\mycomputer\node_modules\bower\lib\core\Manager.js:323:51)
    at Array.forEach (native)
    at Manager.resolve (c:\Users\mycomputer\node_modules\bower\lib\core\Manager.js:116:23)
    at Project._bootstrap (c:\Users\mycomputer\node_modules\bower\lib\core\Project.js:559:6)
    at c:\Users\mycomputer\node_modules\bower\lib\core\Project.js:75:21

Console trace:
Error
    at StandardRenderer.error (c:\Users\mycomputer\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (c:\Users\mycomputer\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:191:7)
    at Logger.emit (c:\Users\mycomputer\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at c:\Users\mycomputer\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (c:\Users\mycomputer\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at c:\Users\mycomputer\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (c:\Users\mycomputer\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (c:\Users\mycomputer\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 7.8.0
OS: Windows_NT 10.0.10586 x64
```

### Versions:
```bat
C:\> npm -v
4.2.0

C:\> bower -v
1.8.0
```
### `bower-art-resolver` installation:
```bat

C:\> npm install -g --save bower-art-resolver
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

C:\Users\mycomputer\node_modules
`-- bower-art-resolver@2.0.8

C:\> npm -g list | grep art
`-- bower-art-resolver@2.0.8
```

### The `.bowerrc`
```bat
C:\> type %USERPROFILE%\.bowerrc
{
  "registry": "http://my.artifactory.com/artifactory/api/bower/bower",
  "resolvers": [
    "bower-art-resolver"
  ]
}
```

### Result:
- The exact same .bowerrc works in Linux environment
- But it cannot work in Windows Command Line environment.

I've tried to add the `c:\Users\mycomputer\node_modules\node_modules\bower-art-resolver\` in the **System Environment Variable** -> **PATH**. But this setting still doesn't work.

**Comment by marslo** [comment]
Okay. I've added the `c:\Users\mycomputer\node_modules\node_modules\bower-art-resolver\node_modules\.bin\` to `%PATH%` and still doesn't work

**Comment by marslo** [comment]
Can any one help me?
Thanks.

**Comment by eyalbe4** [comment]
Sorry for the late response @Marslo.
We're checking this.

**Comment by marslo** [comment]
Thank you @eyalbe4. If you need any input I can help.

**Comment by eyalbe4** [comment]
@Marslo, we've been trying to reproduce this issue, but everything seems to be working for us.
We used Windows 10 with bower 1.8.0 and the latest bower-art-resolver version.
The only idea we currently have is to try and uninstall bower and the resolver and then wipe the npm cache:
> npm uninstall -g bower-art-resolver
> npm uninstall -g bower
> npm cache clean
> npm install -g bower
> npm install -g bower-art-resolver
> bower install bootstrap
